# permissions for end users to view simpleproxyclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: simpleproxyclient-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keycloakerator
    app.kubernetes.io/part-of: keycloakerator
    app.kubernetes.io/managed-by: kustomize
  name: simpleproxyclient-viewer-role
rules:
- apiGroups:
  - dapla.ssb.no
  resources:
  - simpleproxyclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dapla.ssb.no
  resources:
  - simpleproxyclients/status
  verbs:
  - get
